In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [22]:
data=pd.read_csv(r"C:\Users\HP\Desktop\Salaries.csv")

In [23]:
data.head()

Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750
3           4      Prof          B             45           39  Male  115000
4           5      Prof          B             40           41  Male  141500

In [37]:
X = data.iloc[:, [3, 4, 6]].values
y = data.iloc[:, -1].values

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
 

In [52]:
from sklearn.preprocessing import StandardScaler
ss= StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [53]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [67]:
y_pred  =  classifier.predict(X_test)
y_pred  

array([101000,  74000, 111350,  85000,  84500, 105000, 105000,  90215,
        77000, 111350, 105000, 105000, 133700,  75996, 105000, 138000,
       152664, 105000, 139750,  83001,  92000,  74000,  84500, 141136,
       120806,  86895, 105000, 134800, 122960, 163200,  92000, 134550,
        92000, 121946,  92000,  92000, 111350, 105000, 126200, 101000,
       172505, 166800, 101000, 105000, 111350, 101000, 133900, 111350,
       105000, 105000, 101000,  81500, 124750,  74000, 118223, 128464,
       111350, 105000,  92000, 143250, 111350,  72500,  83001, 118700,
        83001, 134550,  95408, 105000, 146000, 146856,  74000, 111350,
        92000, 168500, 105000,  92000,  72500, 115800,  88000, 101000,
        72500,  81500,  72500, 163200, 105000, 186960,  74830,  92000,
        92700,  74000, 118971, 118971, 105000, 111350, 127512, 126000,
       111350,  92000, 101000, 105000,  80225,  92000, 105000, 134550,
       150743, 111350, 163200,  92000, 105000, 163200, 101000, 105000,
      

In [69]:
y_test

array([100522,  77500, 113398,  86100,  86373, 103760, 104800,  90304,
        77700, 109646, 107100, 108100, 133217,  75044, 107986, 134185,
       151575, 105450, 136000,  83000,  91000,  74000,  81035, 150480,
       116518,  88650, 106231, 131950, 124312, 168635,  92550, 135027,
        92000, 119500,  95436,  91227, 111751, 107309, 127100,  97032,
       175000, 173200,  97150, 104428, 109954,  97262, 136500, 109305,
       104279, 106608, 101210,  81500, 129600,  74692, 119800, 134885,
       114778, 103275,  90000, 141500, 114500,  69200,  82600, 117150,
        82099, 137167,  97000, 103994, 145350, 147765,  74000, 111512,
        89565, 189409, 104800,  89650,  69700, 119015,  88795,  96614,
        68404,  83900,  71065, 153303, 107550, 192253,  78182,  88600,
        92700,  77081, 117704, 119250, 107300, 112696, 124714, 122875,
       110515,  92000, 101100, 103613,  77500,  90450, 103600, 135585,
       142023, 109000, 155865,  95611, 107008, 170500, 102580, 103750,
      

In [56]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [68]:
print(metrics.accuracy_score(y_test, y_pred))

0.05
